- name: program for variables from files
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: print the host information
    ansible.builtin.debug:
      msg: "hi, {{course}}, duration is : {{duration}}, traineer is : {{traineer}}"