- name: this program for variable prompt
  hosts: web
  vars_prompt:
  - name: course
    prompt: enter the course name
  - name: duration
    prompt: enter the duration time
  - name: traineer
    prompt: enter the traineer name
  tasks:
   - name : print the prompt information
     ansible.builtin.debug:
       msg: "hi, {{course}}, duration is : {{duration}}, traineer is : {{traineer}}"