- name: this program for variable prompt
  hosts: web
  vars_prompt:
  - name: course
    prompt: enter the course name
    private: false
  - name: duration
    prompt: enter the duration time
  - name: traineer
    private: false
    prompt: enter the traineer name
    private: false
  tasks:
   - name : print the prompt information
     ansible.builtin.debug:
       msg: "hi, {{course}}, duration is : {{duration}}, traineer is : {{traineer}}"