- name: data types usage
  hosts: local
  connection: local
  vars:
    course: "devops with aws"
    duration: 111
    topics:
    - linux
    - shell
    - ansible
    - terraform
    - aws
    live: true
    tools: 
      ci: jenkins
      cm: ansible
      cloud: aws
      aws:
      - iam
      - s3
  tasks:
  - name: print the data information
    ansible.builtin.debug:
      msg: "hi, i am learning {{course}}, with duration {{duration}}, topics are {{topics}}, live{{live}}, tools are {{tools}}"