- name: progrmme for filters
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
       msg: "hello {{ course | default('ansible') }}"
        # msg: " {{ course }} "

  - name: print the name in uppercase
    vars: 
     greeting: "hello ramesh"
    ansible.builtin.debug:
      msg: " {{ greeting | upper}} "

  
  - name: print the name in lowercase
    vars:
     greeting: "HELLO RAMESH"
    ansible.builtin.debug:
      msg: " {{ greeting | lower}} "

  - name: print the unique values
    vars: 
     number: [1,2,2,1,3,4,3,4,5,6,7,8,5,9,10]
    ansible.builtin.debug:
      msg: " {{ number | unique }} "

  - name: print the max and min values
    vars:
     number: [23,67,123,34,78,899]
    ansible.builtin.debug:
      msg: " min: {{ number | min }}, max: {{ number | max}} "

  - name: convert map to list
    vars:
      course:
        name: "devops with aws"
        duration: 111
        trainer: "shiva"
    ansible.builtin.debug:
      msg: " {{ course | dict2items}}"
      
  - name: check the ip address
    vars:
      myip: "172.31.89.121"
    ansible.builtin.debug:
      msg: " {{ myip | ansible.utils.ipv4 }}"
      