- name: progrmme for filters
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      # msg: "hello {{ course | default('ansible') }}"
        msg: " {{ course }} "