- name: progrmme for filters
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
       msg: "hello {{ course | default('ansible') }}"
        # msg: " {{ course }} "

  - name: print the name in uppercase
    vars: 
     greeting: "hello ramesh"
    ansible.builtin.debug:
      msg: " {{ greeting | upper}} "

  
  - name: print the name in lowercase
    vars:
     greeting: "HELLO RAMESH"
    ansible.builtin.debug:
      msg: " {{ greeting | lower}} "