- name: command vs shell
  hosts: local
  connection: local
  tasks:
  - name: excute the value
    ansible.builtin.shell: ls -ltr > /tmp/output.txt

- name: check the process
  ansible.builtin.command: ps -ef | grep ssh
  register: output